# Packages: isort for formatting imports, black for formatting code
# pylint for linting code and pytest for testing code in test dir
name: Code Prep: Format, lint and test
on: [push, pull]
  branches:
    - master
    - main

job:
  format-lint: # job name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # use a github action
      
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # use a github action
      
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7

