# Packages: isort for formatting imports, black for formatting code
# pylint for linting code and pytest for testing code in test dir

name: Code Prep - Format, lint and test

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  fix-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # use a github action
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: python -m pip install pytest -r requirements.dev.txt

      - name: Format with black
        run: black app

      - name: Sort imports with isort
        run: isort app

      - name: lint with pylint
        run: pylint app --fail-under=7.0
      
      - name: Test with pytest
        run: pytest

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit isort and black updates
        run: git commit -am "github actions formatting"